const DESCRIPTION_LINK_REGEX = /\[.*?\]\{.*?:(.*?)\}/;

const STAT_STAGE_MULTIPLIERS: Record<string, number> = {
  '-6': 2 / 8,
  '-5': 2 / 7,
  '-4': 2 / 6,
  '-3': 2 / 5,
  '-2': 2 / 4,
  '-1': 2 / 3,
  '0': 2 / 2,
  '1': 3 / 2,
  '2': 4 / 2,
  '3': 5 / 2,
  '4': 6 / 2,
  '5': 7 / 2,
  '6': 8 / 2,
};

const MOVE_META_CATEGORIES = [
  'Inflicts damage',
  'No damage; inflicts status ailment',
  "No damage; lowers target's stats or raises user's stats",
  'No damage; heals the user',
  'Inflicts damage; inflicts status ailment',
  "No damage; inflicts status ailment; raises target's stats",
  "Inflicts damage; lowers target's stats",
  "Inflicts damage; raises user's stats",
  'Inflicts damage; absorbs damage done to heal the user',
  'One-hit KO',
  'Effect on the whole field',
  'Effect on one side of the field',
  'Forces target to switch out',
  'Unique effect',
];

const MOVE_AILMENTS: Record<string, string> = {
  '-1': '????',
  '0': 'null',
  '1': 'Paralysis',
  '2': 'Sleep',
  '3': 'Freeze',
  '4': 'Burn',
  '5': 'Poison',
  '6': 'Confusion',
  '7': 'Infatuation',
  '8': 'Trap',
  '9': 'Nightmare',
  '12': 'Torment',
  '13': 'Disable',
  '14': 'Yawn',
  '15': 'Heal Block',
  '17': 'No type immunity',
  '18': 'Leech Seed',
  '19': 'Embargo',
  '20': 'Perish Song',
  '21': 'Ingrain',
  '24': 'Silence',
};

const TYPES = [
  null,
  'Normal',
  'Fighting',
  'Flying',
  'Poison',
  'Ground',
  'Rock',
  'Bug',
  'Ghost',
  'Steel',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Psychic',
  'Ice',
  'Dragon',
  'Dark',
  'Fairy',
  '???',
  'Shadow',
];

const MOVE_TARGETS = [
  null,
  'One specific move. How this move is chosen depends upon on the move being used.',
  'One other Pokémon on the field, selected by the trainer. Stolen moves reuse the same target.',
  "The user's ally (if any).",
  "The user's side of the field. Affects the user and its ally (if any).",
  'Either the user or its ally, selected by the trainer.',
  'The opposing side of the field. Affects opposing Pokémon.',
  'The user.',
  'One opposing Pokémon, selected at random.',
  'Every other Pokémon on the field.',
  'One other Pokémon on the field, selected by the trainer.',
  'All opposing Pokémon.',
  'The entire field. Affects all Pokémon.',
  'The user and its allies.',
  'Every Pokémon on the field.',
];

const DAMAGE_CLASSES = [null, 'Status', 'Physical', 'Special'];

const TYPE_EFFICACY = [
  null,
  [null, 1, 1, 1, 1, 1, 0.5, 1, 0, 0.5, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  [null, 2, 1, 0.5, 0.5, 1, 2, 0.5, 0, 2, 1, 1, 1, 1, 0.5, 2, 1, 2, 0.5],
  [null, 1, 2, 1, 1, 1, 0.5, 2, 1, 0.5, 1, 1, 2, 0.5, 1, 1, 1, 1, 1],
  [null, 1, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2],
  [null, 1, 1, 0, 2, 1, 2, 0.5, 1, 2, 2, 1, 0.5, 2, 1, 1, 1, 1, 1],
  [null, 1, 0.5, 2, 1, 0.5, 1, 2, 1, 0.5, 2, 1, 1, 1, 1, 2, 1, 1, 1],
  [null, 1, 0.5, 0.5, 0.5, 1, 1, 1, 0.5, 0.5, 0.5, 1, 2, 1, 2, 1, 1, 2, 0.5],
  [null, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5, 1],
  [null, 1, 1, 1, 1, 1, 2, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 1, 2, 1, 1, 2],
  [null, 1, 1, 1, 1, 1, 0.5, 2, 1, 2, 0.5, 0.5, 2, 1, 1, 2, 0.5, 1, 1],
  [null, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0.5, 0.5, 1, 1, 1, 0.5, 1, 1],
  [null, 1, 1, 0.5, 0.5, 2, 2, 0.5, 1, 0.5, 0.5, 2, 0.5, 1, 1, 1, 0.5, 1, 1],
  [null, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0.5, 0.5, 1, 1, 0.5, 1, 1],
  [null, 1, 2, 1, 2, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 0.5, 1, 1, 0, 1],
  [null, 1, 1, 2, 1, 2, 1, 1, 1, 0.5, 0.5, 0.5, 2, 1, 1, 0.5, 2, 1, 1],
  [null, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 1, 1, 2, 1, 0],
  [null, 1, 0.5, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5, 0.5],
  [null, 1, 2, 1, 0.5, 1, 1, 1, 1, 0.5, 0.5, 1, 1, 1, 1, 1, 2, 2, 1],
];

const ARTISTS = {
  '405452200656109569': 'HiroWilde',
  '304098467192635392': '@superjedi224',
  '130438329484181504': '@haltfire302',
  // ... (remaining ARTISTS data omitted for brevity)
};

const NATURES = [
  'Adamant',
  'Bashful',
  'Bold',
  'Brave',
  'Calm',
  'Careful',
  'Docile',
  'Gentle',
  'Hardy',
  'Hasty',
  'Impish',
  'Jolly',
  'Lax',
  'Lonely',
  'Mild',
  'Modest',
  'Naive',
  'Naughty',
  'Quiet',
  'Quirky',
  'Rash',
  'Relaxed',
  'Sassy',
  'Serious',
  'Timid',
];

const STAT_NAMES: Record<string, string> = {
  hp: 'HP',
  atk: 'Attack',
  defn: 'Defense',
  satk: 'Sp. Atk',
  sdef: 'Sp. Def',
  spd: 'Speed',
  evasion: 'Evasion',
  accuracy: 'Accuracy',
  crit: 'Critical Hit',
};

const STARTER_GENERATION = {
  'Generation I (Kanto)': ['Bulbasaur', 'Charmander', 'Squirtle'],
  'Generation II (Johto)': ['Chikorita', 'Cyndaquil', 'Totodile'],
  'Generation III (Hoenn)': ['Treecko', 'Torchic', 'Mudkip'],
  'Generation IV (Sinnoh)': ['Turtwig', 'Chimchar', 'Piplup'],
  'Generation V (Unova)': ['Snivy', 'Tepig', 'Oshawott'],
  'Generation VI (Kalos)': ['Chespin', 'Fennekin', 'Froakie'],
  'Generation VII (Alola)': ['Rowlet', 'Litten', 'Popplio'],
  'Generation VIII (Galar)': ['Grookey', 'Scorbunny', 'Sobble'],
  'Generation IX (Paldea)': ['Sprigatito', 'Fuecoco', 'Quaxly'],
};

const STARTER_POKEMON = Object.values(STARTER_GENERATION)
  .flat()
  .map(item => item.toLowerCase());

const SORTING_FUNCTIONS = {
  number: 'idx',
  iv: 'iv_total',
  level: 'level',
  pokedex: 'species_id',
  price: 'market_data.price',
  bid: 'auction_data.current_bid',
  ends: 'auction_data.ends',
  id: '_id',
};

const DEFAULT_DESCENDING = new Set(['iv', 'level']);

const FILTER_BY_NUMERICAL = {
  iv: 'iv_total',
  level: 'level',
  hpiv: 'iv_hp',
  atkiv: 'iv_atk',
  defiv: 'iv_defn',
  spatkiv: 'iv_satk',
  spdefiv: 'iv_sdef',
  spdiv: 'iv_spd',
};

const FILTER_BY_DUPLICATES = {
  triple: 3,
  quadruple: 4,
  pentuple: 5,
  hextuple: 6,
};

const IV_FIELDS = [
  'iv_hp',
  'iv_atk',
  'iv_defn',
  'iv_satk',
  'iv_sdef',
  'iv_spd',
];

const NATURE_MULTIPLIERS: Record<string, Record<string, number>> = {
  Hardy: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Lonely: {
    hp: 1,
    atk: 1.1,
    defn: 0.9,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Brave: {
    hp: 1,
    atk: 1.1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 0.9,
  },
  Adamant: {
    hp: 1,
    atk: 1.1,
    defn: 1,
    satk: 0.9,
    sdef: 1,
    spd: 1,
  },
  Naughty: {
    hp: 1,
    atk: 1.1,
    defn: 1,
    satk: 1,
    sdef: 0.9,
    spd: 1,
  },
  Bold: {
    hp: 1,
    atk: 0.9,
    defn: 1.1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Docile: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Relaxed: {
    hp: 1,
    atk: 1,
    defn: 1.1,
    satk: 1,
    sdef: 1,
    spd: 0.9,
  },
  Impish: {
    hp: 1,
    atk: 1,
    defn: 1.1,
    satk: 0.9,
    sdef: 1,
    spd: 1,
  },
  Lax: {
    hp: 1,
    atk: 1,
    defn: 1.1,
    satk: 1,
    sdef: 0.9,
    spd: 1,
  },
  Timid: {
    hp: 1,
    atk: 0.9,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1.1,
  },
  Hasty: {
    hp: 1,
    atk: 1,
    defn: 0.9,
    satk: 1,
    sdef: 1,
    spd: 1.1,
  },
  Serious: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Jolly: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 0.9,
    sdef: 1,
    spd: 1.1,
  },
  Naive: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 0.9,
    spd: 1.1,
  },
  Modest: {
    hp: 1,
    atk: 0.9,
    defn: 1,
    satk: 1.1,
    sdef: 1,
    spd: 1,
  },
  Mild: {
    hp: 1,
    atk: 1,
    defn: 0.9,
    satk: 1.1,
    sdef: 1,
    spd: 1,
  },
  Quiet: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1.1,
    sdef: 1,
    spd: 0.9,
  },
  Bashful: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
  Rash: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1.1,
    sdef: 0.9,
    spd: 1,
  },
  Calm: {
    hp: 1,
    atk: 0.9,
    defn: 1,
    satk: 1,
    sdef: 1.1,
    spd: 1,
  },
  Gentle: {
    hp: 1,
    atk: 1,
    defn: 0.9,
    satk: 1,
    sdef: 1.1,
    spd: 1,
  },
  Sassy: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1.1,
    spd: 0.9,
  },
  Careful: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 0.9,
    sdef: 1.1,
    spd: 1,
  },
  Quirky: {
    hp: 1,
    atk: 1,
    defn: 1,
    satk: 1,
    sdef: 1,
    spd: 1,
  },
};

const URL_REGEX =
  /(([a-z]{3,6}:\/\/)|(^|\s))([a-zA-Z0-9\-]+\.)+[a-z]{2,13}[\.\?\=\&\%\/\w\-]*\b([^@]|$)/;
const PINK = 0xfe9ac9;
const BLUE = 0x9ccfff;

export default {
  NATURE_MULTIPLIERS,
  STARTER_POKEMON,
  STARTER_GENERATION,
  SORTING_FUNCTIONS,
  DEFAULT_DESCENDING,
  FILTER_BY_NUMERICAL,
  FILTER_BY_DUPLICATES,
  IV_FIELDS,
  STAT_NAMES,
  PINK,
  BLUE,
  URL_REGEX,
  DESCRIPTION_LINK_REGEX,
  NATURES,
  STAT_STAGE_MULTIPLIERS,
  MOVE_META_CATEGORIES,
  MOVE_AILMENTS,
  TYPES,
  MOVE_TARGETS,
  DAMAGE_CLASSES,
  TYPE_EFFICACY,
  ARTISTS,
};
